### PR TITLE
Changed from extending ImageView to extending AppCompatImageView

### PR DESCRIPTION
**Pull request by extorn**
I've migrated my change from the old repo to this one now.
I'm new to Android development, so if it doesn't make sense, please let me know why.
Thanks

### CODE REVIEW

**Comment by Ruberik** [comment]
@hannesa2, note that you merged this into the AndroidX branch and not the main branch.

**Comment by hannesa2** [comment]
Thank you for your PR.
But ups, you made your PR to the `AndroidX` branch !
This `AndroidX` is already merged, so I will apply it to `master`

**Comment by hannesa2** [comment]
please see https://github.com/hannesa2/TouchImageView/pull/10

**Comment by extorn** [comment]
sorry. I've not seen that branch strategy before. I'll make future changes against master.

**Pull request merged**
