### PR TITLE
Makes handling of rotation and resizing configurable

### LINKED ISSUE #4: On rotation, zoom is retained but position isn't
To reproduce:

1. Open the sample app in portrait mode.
2. Tap "single touchimageview"
3. Zoom in as much as possible to the bottom-right corner.
4. Rotate to landscape mode.

Expected result: The TouchImageView either:
1. Displays 1.0 zoom, as if the Activity had been opened in landscape mode in the first place, OR
2. Retains its zoom, as well as _something like_ its position.

Actual result:
The TouchImageView retains its zoom, in the top-left corner of the image.

I believe my expected result 2 was intended, because (a) there's a function called translateMatrixAfterRotate, and (b) translateMatrixAfterRotate sure seems to be trying to translate the image to a spot with a similar centre after a rotation change.

### PR DESCRIPTION
**Pull request by Ruberik**
This is a big PR, and I've left the various changes that went into it so you can see how I built it, in case that's helpful. There will be a few bugs along the way; I've squashed all the ones I'm aware of.

Before looking at the code, I suggest running the sample app and loading "Resize Example" to see what's new.

Specifically what this adds to the public interface is:

1. Allows the user to specify which part of the image should remain fixed when the orientation changes, via setOrientationChangeFixedPixel. This fixes #4, and therefore **this represents a behaviour change**.
2. Allows the user to specify which part of the image should remain fixed when the size of the TouchImageView otherwise changes. This is really the important thing; play around with how it feels when you resize in the sample app with the various settings. MikeOrtiz's original version had behaviour equivalent to CENTER. The current version of this library is equivalent to TOP_LEFT; however I don't think that change was intentional, and I believe CENTER is a more reasonable default, so that's what I set it to. **This represents a behaviour change**.
3. Adds setMinZoom(TouchImageView.AUTOMATIC_MIN_ZOOM), which lets the user zoom out to see the whole image, if the scaleType is set to CENTER or CENTER_CROP. IMO this should be the new default, but that would be a behaviour change so I didn't change it.
4. Adds setMaxZoomRatio(double ratio), which lets the user zoom in to minZoom * ratio. Especially convenient if you're using AUTOMATIC_MIN_ZOOM.

### CODE REVIEW

**Comment by hannesa2** [comment]
Cool !
But give me some time to check. If you have some additions for README.md , everyone is happy to read some (only necessary) info

**Comment by Ruberik** [comment]
Good thought; I'll do that. And I'm happy to hear other feedback.

**Comment by hannesa2** [comment]
I tried how it's behave if I use RESIZE TOP_LEFT and ROTATE TOP_LEFT when I'm in zoom in bottom right corner. So I changed image to see corner better.
This is the result:

Image wasn't kept , so I can't test behavior. Please check

rotate-image

**Comment by hannesa2** [comment]
I merge it, maybe you find some time to fix the example

**Comment by Ruberik** [comment]
Thanks for catching that! Humorously, I had left a comment in the source saying that I don't need to call setDrawable, which I actually do. Fixed in #6.

**Pull request merged**
